// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	FindProductByCategory(ctx context.Context, arg FindProductByCategoryParams) ([]Product, error)
	FindSellerProducts(ctx context.Context, arg FindSellerProductsParams) ([]Product, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserCodeAndExpiry(ctx context.Context, arg UpdateUserCodeAndExpiryParams) (User, error)
	UpdateUserToSeller(ctx context.Context, arg UpdateUserToSellerParams) (User, error)
	UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) (User, error)
}

var _ Querier = (*Queries)(nil)
